# Group17 Analysis Code

```{r}
library(corrplot)
library(dplyr)
library(car)
```

```{r}
# load the data and select variabls in research question
diabetes <- read.csv('diabetes_dataset.csv')
```

## Data Cleaning

```{r}
# check if there are missing values and summarize dataset
colSums(is.na(diabetes))
summary(diabetes)
```

```{r}
# In reality, LDL and HDL must larger than 0.
# mutate categorical variables to factor
diabetes_clean <- diabetes %>%
  filter(LDL>0, HDL>0) %>%
  mutate(Outcome = factor(Outcome, levels=c(0,1), labels=c("No Diabetes","Diabetes")),
         FamilyHistory = factor(FamilyHistory, levels=c(0,1), labels=c("No Diabetes History","Has Diabetes History")),
         DietType = factor(DietType, levels=c(0,1,2), labels=c("Unbalanced", "Balanced", "Vegan")),
         Hypertension = factor(Hypertension, levels=c(0,1), labels=c("No Hypertension","Hypertension")),
         MedicationUse = factor(MedicationUse, levels=c(0,1), labels=c("Not Taking Medicine","Taking Medicine")))
summary(diabetes_clean)
```

## EDA

### Heatmap (Correlation between some covariates)

```{r}
# The correlation of BMI, WaistCircumference, HipCircumference and WHR (All of them are obesity indicators).
# The correlation of Glucose and HbA1c (Both of them are sugar blood indicators).
cor_obesity <- diabetes_clean %>%
  select(BMI, WaistCircumference, HipCircumference, WHR)
cor_sugar <- diabetes_clean %>%
  select(Glucose, HbA1c)

corrplot(cor(cor_obesity), method = "color", addCoef.col = "white")
title("Figure 1: Correlation Matrix of BMI, WaistCircumference, HipCircumference and WHR", cex.main = 0.9)

corrplot(cor(cor_sugar), method = "color", addCoef.col = "white")
title("Figure 2: Correlation Matrix of Glucose and HbA1c", cex.main = 0.9)
```

```{R}
# drop WaistCircumference, HipCircumference and Glucose
diabetes_selected <- diabetes_clean %>%
  select(-WaistCircumference, -HipCircumference, -Glucose)
```

### Covariate

```{r}
# boxplots for response and continuous covariate

# boxplot between Age and Outcome
boxplot(Age ~ Outcome,
        data = diabetes_selected,
        main = "Figure 3: Age by Diabetes Status",
        xlab = "Diabetes",
        ylab = "Age",
        col = c("lightblue", "salmon"))

# boxplot between Pregnancies and Outcome
boxplot(Pregnancies ~ Outcome,
        data = diabetes_selected,
        main = "Figure 4: Pregnancies by Diabetes Status",
        xlab = "Diabetes",
        ylab = "The number of pregnant times",
        col = c("lightblue", "salmon"))

# boxplot between BMI and Outcome
boxplot(BMI ~ Outcome,
        data = diabetes_selected,
        main = "Figure 5: BMI by Diabetes Status",
        xlab = "Diabetes",
        ylab = "Body Mass Index (kg/m²)",
        col = c("lightblue", "salmon"))

# boxplot between BloodPressure and Outcome
boxplot(BloodPressure ~ Outcome,
        data = diabetes_selected,
        main = "Figure 6: BloodPressure by Diabetes Status",
        xlab = "Diabetes",
        ylab = "Systolic blood pressure (mmHg)",
        col = c("lightblue", "salmon"))

# boxplot between HbA1c and Outcome
boxplot(HbA1c ~ Outcome,
        data = diabetes_selected,
        main = "Figure 7: HbA1c Level by Diabetes Status",
        xlab = "Diabetes",
        ylab = "HbA1c Level (%)",
        col = c("lightblue", "salmon"))

# boxplot between LDL and Outcome
boxplot(LDL ~ Outcome,
        data = diabetes_selected,
        main = "Figure 8: LDL by Diabetes Status",
        xlab = "Diabetes",
        ylab = "Low-Density Lipoprotein (mg/dL)",
        col = c("lightblue", "salmon"))

# boxplot between HDL and Outcome
boxplot(HDL ~ Outcome,
        data = diabetes_selected,
        main = "Figure 9: HDL by Diabetes Status",
        xlab = "Diabetes",
        ylab = "High-Density Lipoprotein (mg/dL)",
        col = c("lightblue", "salmon"))

# boxplot between Triglycerides and Outcome
boxplot(Triglycerides ~ Outcome,
        data = diabetes_selected,
        main = "Figure 10: Triglycerides by Diabetes Status",
        xlab = "Diabetes",
        ylab = "Fat levels in the blood (mg/dL)",
        col = c("lightblue", "salmon"))

# boxplot between WHR and Outcome
boxplot(WHR ~ Outcome,
        data = diabetes_selected,
        main = "Figure 11: WHR by Diabetes Status",
        xlab = "Diabetes",
        ylab = "Waist circumference divided by hip circumference",
        col = c("lightblue", "salmon"))
```
```{R}
# Log transformation to BMI, BloodPressure, Hb1Ac (reduce outlier)
diabetes_scaled <- diabetes_selected %>%
  mutate(BMI = log(BMI), BloodPressure = log(BloodPressure), HbA1c = log(HbA1c))

# boxplot between log(BMI) and Outcome
boxplot(BMI ~ Outcome,
        data = diabetes_scaled,
        main = "Figure 12: log(BMI) by Diabetes Status",
        xlab = "Diabetes",
        ylab = "Log Transformation of Body Mass Index (kg/m²)",
        col = c("lightblue", "salmon"))

# boxplot between log(BloodPressure) and Outcome
boxplot(BloodPressure ~ Outcome,
        data = diabetes_scaled,
        main = "Figure 13: log(BloodPressure) by Diabetes Status",
        xlab = "Diabetes",
        ylab = "Log Transformation of Systolic blood pressure (mmHg)",
        col = c("lightblue", "salmon"))

# boxplot between log(HbA1c) and Outcome
boxplot(HbA1c ~ Outcome,
        data = diabetes_scaled,
        main = "Figure 14: log(HbA1c Level) by Diabetes Status",
        xlab = "Diabetes",
        ylab = "Log Transformation of HbA1c Level (%)",
        col = c("lightblue", "salmon"))
```

```{r}
# contingency tables for response and categorical covariate

# contingency table for Outcome and FamilyHistory
table(diabetes_scaled$Outcome, diabetes_scaled$FamilyHistory)
print("Tabel 1: Contingency Table of Outcome and FamilyHistory")

# contingency table for Outcome and DietType
table(diabetes_scaled$Outcome, diabetes_scaled$DietType)
print("Tabel 2: Contingency Table of Outcome and DietType")

# contingency table for Outcome and Hypertension
table(diabetes_scaled$Outcome, diabetes_scaled$Hypertension)
print("Tabel 3: Contingency Table of Outcome and Hypertension")

# contingency table for Outcome and MedicationUse
table(diabetes_scaled$Outcome, diabetes_scaled$MedicationUse)
print("Tabel 4: Contingency Table of Outcome and MedicationUse")
```

```{R}
# Drop Pregnancies, LDL, HDL, Triglycerides, WHR (nearly no difference), Hypertension (imbalance) and MedicationUse.
diabetes_selected_eda <- diabetes_scaled %>%
  select(-Pregnancies, -LDL, -HDL, -Triglycerides, -WHR, -Hypertension, -MedicationUse)
summary(diabetes_selected_eda)
```

## Statistical Analysis

### Assumption

```{R}
#| warning: false
# fit full model and check VIF 
full_model <- glm(Outcome ~ ., data = diabetes_selected_eda, family = binomial)
vif(full_model)
print("Table 5: VIF for Full Logistic Model")
```

```{R}
# use Cook's distance to find if there is influential point
cooks_rule_of_thumb <- cooks.distance(full_model)
plot(cooks_rule_of_thumb, xlab="Individual i", ylab="Cook's Distance")
abline(h=1, lty=2, col="red")
title("Figure 15: Cook's Distance for rule-of-thumb (>1)")
```
### Model Selection

```{R}
#| warning: false
# apply backward method (based on AIc)
summary(step(full_model))
```
```{R}
#| warning: false
# model selected by backward method
backward_selected_model <- glm(formula = Outcome ~ Age + BMI + HbA1c + FamilyHistory, data = diabetes_selected_eda, family = binomial)
summary(backward_selected_model)
```
